### PR TITLE
Added Lab 2 MATLAB Livescript and HTML files.

### PR DESCRIPTION
**Pull request by conawt**
Ready for review. @Avis07

### CODE REVIEW

**Comment by Avis07** [comment]
Hey, here are my recommendations for edits: 

1A: Just a minor thing, I would add a legend for your plot so we can tell which graph refers to which convoluted distribution, as it is not possible to tell right now. 

1B: You mention that the "sum of independent variables is independent", but I found this to be a little confusing. It might just be my lack of understanding, but maybe you could elaborate on this and how it relates to the fact that the convoluted Poisson distribution is still a Poisson distribution?

1C: You talk about how the Poisson distribution approximates a Gaussian for very large means - I know this is true, but maybe it would be helpful to provide a little more justification for why this is so. 

2: This may be more on my end, but I was a little confused as to why you were normalizing your distributions by dividing them by their sum. I see how this ensures that each of your distributions has the same width and just a different amplitude, but I was unsure as to why this is actually necessary. In my lab my distributions remained centered around the same point but drastically varied in width, so I am wondering if you are maybe actually losing some important information by trying to normalize them the way that you do? But that is purely conjecture so feel free to ignore this and continue normalizing as you have done so far. 

2B: Nothing to say here, I thought you did a really good job of creating a new Gaussian from the convoluted Rayleigh distribution and comparing it to the averaged Rayleigh. This was a very clear and easy to follow section, nice job! 

3B: The actual math and operation to incorporate the trials factor into the probability calculations is very straightforward, but maybe you could give some more theoretical justification as to why we can just sum the probability density function for the single pixel 10,000 times? You already kind of touch on this in your written answer, so perhaps this edit isn't necessary at all - entirely at your discretion. 

3C: It is surprising that the sigma value drops, maybe you could give some insight into why it does? 

4: This entire problem was done really straightforwardly and made a lot of sense, nice work! 

ALL IN ALL: Very clear and well done lab, I couldn't find any procedural or systematic errors in your lab, so I think really the most you can do to improve is to elaborate on your theoretical explanations even more than you already have, just to make sure that the entire theoretical background for the lab is well explained.

**Comment by conawt** [comment]
I've finished the final draft and made changes based on feedback:

- Added legends, labels, and other features to make plots easier to read.
- Clarified and elaborated on confusing sections.
- Discussed my decision to normalize the area for some graphs. The goal was to differentiate between probability and probability _density_. This was just my preference on how to read and present the graphs.

I also made an effort to discuss the lab more in writing so that a reader can follow it, as well as general improvements overall.

**Comment by conawt** [comment]
Ready to be graded. @oliviatessa

**Comment by oliviatessa** [comment]
Hi Thomas, 
Here are my comments on your lab 2: 
P.1
- Great plots but it would be more helpful to the reader if you explained what each plot is saying right after the plot (or add captions) 
P.2 
- The log plot is great - great job remembering the tails! 
- You've referenced the CLT a couple times at this point and I would suggest briefly explaining the theorem to make the whole report more comprehensive. 
P.4 
- Really like this last plot, it really illustrates your point. 

In general,
- Great improvement! 
- Try adding captions to your figures. It's okay if your captions repeat and summarize what you say in the written parts of your report. When reading scientific papers, most people like to just scan through the figures to get the idea of the paper. 

Note (did not affect your grade at all): I think it's "convolving" rather than "convoluting," but honestly not sure. 

Best, 
Olivia

**Pull request closed without merging**
